from tkinter import Button, Label, Entry, Frame, X, LEFT, RIGHT

def create_controls(self):  # 创建控制按钮
    top_frame = Frame(self.window, bg="#F7F9FB")
    top_frame.pack(pady=6, fill=X)
    op_frame = Frame(top_frame, bg="#F7F9FB")
    op_frame.pack(fill=X, padx=6)
    Label(op_frame, text="值输入（单值或逗号/空格批量）:", font=("Arial",12), bg="#F7F9FB").pack(side=LEFT, padx=(0,6))
    entry = Entry(op_frame, textvariable=self.input_var, width=36, font=("Arial",12))
    entry.pack(side=LEFT, padx=(0,8))
    entry.insert(0, "15,6,23,4,7,71,5")
    Button(op_frame, text="Insert (直接)", command=self.insert_direct, bg="green", fg="white").pack(side=LEFT, padx=4)
    Button(op_frame, text="Insert (动画)", command=self.start_insert_animated, bg="#2E8B57", fg="white").pack(side=LEFT, padx=4)
    Button(op_frame, text="Search (动画)", command=self.start_search_animated, bg="#FFA500").pack(side=LEFT, padx=4)
    Button(op_frame, text="Delete (动画)", command=self.start_delete_animated, bg="red", fg="white").pack(side=LEFT, padx=4)
    Button(op_frame, text="清空", command=self.clear_canvas, bg="orange").pack(side=LEFT, padx=4)
    Button(op_frame, text="返回主界面", command=self.back_to_main, bg="blue", fg="white").pack(side=LEFT, padx=4)
    bottom_frame = Frame(self.window, bg="#F7F9FB")
    bottom_frame.pack(pady=(4,8), fill=X, padx=6)
    left_ops = Frame(bottom_frame, bg="#F7F9FB")
    left_ops.pack(side=LEFT, anchor="w")
    Button(left_ops, text="保存树", command=self.save_tree, bg="#6C9EFF", fg="white").pack(side=LEFT, padx=6)
    Button(left_ops, text="打开树", command=self.load_tree, bg="#6C9EFF", fg="white").pack(side=LEFT, padx=6)
    dsl_ops = Frame(bottom_frame, bg="#F7F9FB")
    dsl_ops.pack(side=RIGHT, anchor="e")
    Label(dsl_ops, text="DSL 命令:", font=("Arial",11), bg="#F7F9FB").pack(side=LEFT, padx=(0,6))
    self.dsl_entry = Entry(dsl_ops, width=36, font=("Arial",11), textvariable=self.dsl_var)
    self.dsl_entry.pack(side=LEFT, padx=(0,6))
    self.dsl_entry.bind("<Return>", lambda e: self.process_dsl())
    Button(dsl_ops, text="执行DSL", command=self.process_dsl).pack(side=LEFT)

def draw_instructions(self):  # 绘制操作说明
    self.canvas.delete("all")
    self.node_items.clear()
    self.node_to_rect.clear()
    self.canvas.create_text(10, 10, anchor="nw", text="BST：插入 / 查找 / 删除 动态演示。中序位置用于横向布局。", font=("Arial",11))
    if self.status_text_id:
        self.canvas.delete(self.status_text_id)
    self.status_text_id = self.canvas.create_text(self.canvas_width-10, 10, anchor="ne", text="", font=("Arial",12,"bold"), fill="darkgreen")