_ALIAS_MAP = {
    "push_to_stack": "stack_push",
    "push_stack": "stack_push",
    "push": "stack_push",
    "push_to_stack_v1": "stack_push",
    "pushstack": "stack_push",
    "pushstack_v1": "stack_push",
    "democlearstack": "stack_clear",
    "clearstack": "stack_clear",
    "clear": "stack_clear",
    
    # 后缀表达式求值别名
    "eval_postfix": "stack_eval_postfix",
    "postfix_eval": "stack_eval_postfix",
    "evaluate_postfix": "stack_eval_postfix",
    "postfix_evaluate": "stack_eval_postfix",
    "calc_postfix": "stack_eval_postfix",
    "postfix_calc": "stack_eval_postfix",
    "rpn_eval": "stack_eval_postfix",
    "reverse_polish_eval": "stack_eval_postfix",
    "stack_postfix": "stack_eval_postfix",
    "stack_rpn": "stack_eval_postfix",
    
    # 括号匹配检验别名
    "bracket_match": "stack_bracket_match",
    "match_brackets": "stack_bracket_match",
    "check_brackets": "stack_bracket_match",
    "brackets_match": "stack_bracket_match",
    "parenthesis_match": "stack_bracket_match",
    "match_parenthesis": "stack_bracket_match",
    "check_parenthesis": "stack_bracket_match",
    "validate_brackets": "stack_bracket_match",
    "brackets_check": "stack_bracket_match",
    "stack_bracket": "stack_bracket_match",
    "stack_brackets": "stack_bracket_match",
    "括号匹配": "stack_bracket_match",
    
    # DFS深度优先搜索别名
    "dfs": "stack_dfs",
    "dfs_visualize": "stack_dfs",
    "depth_first_search": "stack_dfs",
    "depth_first": "stack_dfs",
    "dfs_demo": "stack_dfs",
    "dfs_animation": "stack_dfs",
    "graph_dfs": "stack_dfs",
    "stack_dfs_demo": "stack_dfs",
    "open_dfs": "stack_dfs",
    "show_dfs": "stack_dfs",
    "深度优先": "stack_dfs",
    "深度优先搜索": "stack_dfs",

    "list_insert": "sequence_insert_last",
    "list_append": "sequence_insert_last",
    "list_push": "sequence_insert_last",
    "list_add": "sequence_insert_last",
    "insert_into_list": "sequence_insert_last",
    "seq_list_insert": "sequence_insert_last",
    "sequence_insert": "sequence_insert_last",
    "list_insert_at": "sequence_insert_at",
    "list_insert_pos": "sequence_insert_at",
    "list_insert_position": "sequence_insert_at",
    "list_delete": "sequence_delete_at",
    "list_remove": "sequence_delete_at",
    "seq_list_delete": "sequence_delete_at",
    "list_clear": "sequence_clear",
    "sequenceclear": "sequence_clear",
    "build_list": "sequence_batch_create",
    "sequence_batch_create": "sequence_batch_create",
    "get_list_state": "sequence_get_state",
    "create_sequence_list": "sequence_batch_create",
    "create_list": "sequence_batch_create",
    "create_seq_list": "sequence_batch_create",
    "build_sequence": "sequence_batch_create",
    "create_sequence": "sequence_batch_create",
    "elements_to_list": "sequence_batch_create",
    "clear_sequence_list": "sequence_clear",
    "clear_list_sequence": "sequence_clear",

    # 顺序表逆置别名
    "reverse_list": "sequence_reverse",
    "reverse_sequence": "sequence_reverse",
    "list_reverse": "sequence_reverse",
    "seq_reverse": "sequence_reverse",
    "flip_list": "sequence_reverse",
    "flip_sequence": "sequence_reverse",
    "invert_list": "sequence_reverse",
    "invert_sequence": "sequence_reverse",

    # 顺序表排序别名
    "bubble_sort": "sequence_bubble_sort",
    "bubblesort": "sequence_bubble_sort",
    "bubble": "sequence_bubble_sort",
    "list_bubble_sort": "sequence_bubble_sort",
    "sort_bubble": "sequence_bubble_sort",
    
    "insertion_sort": "sequence_insertion_sort",
    "insertionsort": "sequence_insertion_sort",
    "insert_sort": "sequence_insertion_sort",
    "list_insertion_sort": "sequence_insertion_sort",
    "sort_insertion": "sequence_insertion_sort",
    
    "quick_sort": "sequence_quick_sort",
    "quicksort": "sequence_quick_sort",
    "qsort": "sequence_quick_sort",
    "list_quick_sort": "sequence_quick_sort",
    "sort_quick": "sequence_quick_sort",

    "linked_list_insert_tail": "linked_list_insert_last",
    "linked_list_insert_last": "linked_list_insert_last",
    "linked_list_insert": "linked_list_insert_last",
    "linkedlist_insert": "linked_list_insert_last",
    "linked-list-insert": "linked_list_insert_last",
    "linked_list_push": "linked_list_insert_last",
    "ll_insert": "linked_list_insert_last",
    "linked_list_append": "linked_list_insert_last",
    "linked_list_add": "linked_list_insert_last",
    "linked_list_insert_head": "linked_list_insert_first",
    "linked_list_insert_first": "linked_list_insert_first",
    "linked_list_insert_at": "linked_list_insert_at",
    "linked_list_insert_pos": "linked_list_insert_at",
    "linked_list_insert_position": "linked_list_insert_at",
    "linked_list_delete_at": "linked_list_delete_at",
    "linked_list_remove": "linked_list_delete_at",
    "linked_list_pop": "linked_list_delete_at",
    "linkedlist_delete": "linked_list_delete_at",
    
    # 单链表按值删除别名
    "linked_list_delete_value": "linked_list_delete_value",
    "linked_list_delete_by_value": "linked_list_delete_value",
    "linked_list_remove_value": "linked_list_delete_value",
    "linkedlist_delete_value": "linked_list_delete_value",
    "delete_value": "linked_list_delete_value",
    "remove_value": "linked_list_delete_value",
    "按值删除": "linked_list_delete_value",
    
    # 单链表按值前插入别名
    "linked_list_insert_before": "linked_list_insert_before",
    "linked_list_insert_before_value": "linked_list_insert_before",
    "linkedlist_insert_before": "linked_list_insert_before",
    "insert_before": "linked_list_insert_before",
    "insertbefore": "linked_list_insert_before",
    "在前面插入": "linked_list_insert_before",
    "前插入": "linked_list_insert_before",
    
    # 单链表按值后插入别名
    "linked_list_insert_after": "linked_list_insert_after",
    "linked_list_insert_after_value": "linked_list_insert_after",
    "linkedlist_insert_after": "linked_list_insert_after",
    "insert_after": "linked_list_insert_after",
    "insertafter": "linked_list_insert_after",
    "在后面插入": "linked_list_insert_after",
    "后插入": "linked_list_insert_after",
    
    # 单链表在两值之间插入别名
    "linked_list_insert_between": "linked_list_insert_between",
    "linked_list_insert_between_values": "linked_list_insert_between",
    "linkedlist_insert_between": "linked_list_insert_between",
    "insert_between": "linked_list_insert_between",
    "insertbetween": "linked_list_insert_between",
    "在中间插入": "linked_list_insert_between",
    "之间插入": "linked_list_insert_between",
    
    # 单链表查找别名
    "linked_list_search": "linked_list_search",
    "linked_list_find": "linked_list_search",
    "linkedlist_search": "linked_list_search",
    "linkedlist_find": "linked_list_search",
    "链表查找": "linked_list_search",
    "链表搜索": "linked_list_search",
    "查找节点": "linked_list_search",
    "搜索节点": "linked_list_search",
    
    # 单链表反转别名
    "linked_list_reverse": "linked_list_reverse",
    "linkedlist_reverse": "linked_list_reverse",
    "链表反转": "linked_list_reverse",
    "链表逆置": "linked_list_reverse",
    "反转链表": "linked_list_reverse",
    "逆置链表": "linked_list_reverse",
    "linked_list_clear": "linked_list_clear",
    "clear_linked_list": "linked_list_clear",
    "linked_list_batch_create": "linked_list_batch_create",
    "create_linked_list": "linked_list_batch_create",
    "build_linked_list": "linked_list_batch_create",
    "linked_list_get_state": "linked_list_get_state",
    "get_linked_list_state": "linked_list_get_state",
    "linkedlist_clear": "linked_list_clear",
    "linked_list": "linked_list_get_state",

    # AVL树别名
    "avl_insert": "avl_insert",
    "avl_add": "avl_insert",
    "avl_insert_node": "avl_insert",
    "insert_avl": "avl_insert",
    "avltree_insert": "avl_insert",
    
    "avl_delete": "avl_delete",
    "avl_remove": "avl_delete",
    "avl_delete_node": "avl_delete",
    "delete_avl": "avl_delete",
    "avltree_delete": "avl_delete",
    
    "avl_search": "avl_search",
    "avl_find": "avl_search",
    "avl_lookup": "avl_search",
    "search_avl": "avl_search",
    "find_avl": "avl_search",
    "avltree_search": "avl_search",
    "avl_query": "avl_search",
    
    "avl_clear": "avl_clear",
    "avl_reset": "avl_clear",
    "clear_avl": "avl_clear",
    "avltree_clear": "avl_clear",
    
    "avl_batch_create": "avl_batch_create",
    "avl_create": "avl_batch_create",
    "create_avl": "avl_batch_create",
    "build_avl": "avl_batch_create",
    "avltree_create": "avl_batch_create",
    
    "avl_get_state": "avl_get_state",
    "get_avl_state": "avl_get_state",
    "avl_state": "avl_get_state",
    "avltree_state": "avl_get_state",

    # 红黑树 (RBT) 别名
    "rbt_insert": "rbt_insert",
    "rbt_add": "rbt_insert",
    "rbt_insert_node": "rbt_insert",
    "insert_rbt": "rbt_insert",
    "rbtree_insert": "rbt_insert",
    "red_black_insert": "rbt_insert",
    
    "rbt_delete": "rbt_delete",
    "rbt_remove": "rbt_delete",
    "rbt_delete_node": "rbt_delete",
    "delete_rbt": "rbt_delete",
    "rbtree_delete": "rbt_delete",
    "red_black_delete": "rbt_delete",
    
    "rbt_search": "rbt_search",
    "rbt_find": "rbt_search",
    "rbt_lookup": "rbt_search",
    "search_rbt": "rbt_search",
    "find_rbt": "rbt_search",
    "rbtree_search": "rbt_search",
    "rbt_query": "rbt_search",
    "red_black_search": "rbt_search",
    "red_black_find": "rbt_search",
    
    "rbt_clear": "rbt_clear",
    "rbt_reset": "rbt_clear",
    "clear_rbt": "rbt_clear",
    "rbtree_clear": "rbt_clear",
    "red_black_clear": "rbt_clear",
    
    "rbt_batch_create": "rbt_batch_create",
    "rbt_create": "rbt_batch_create",
    "create_rbt": "rbt_batch_create",
    "build_rbt": "rbt_batch_create",
    "rbtree_create": "rbt_batch_create",
    "red_black_create": "rbt_batch_create",
    
    "rbt_get_state": "rbt_get_state",
    "get_rbt_state": "rbt_get_state",
    "rbt_state": "rbt_get_state",
    "rbtree_state": "rbt_get_state",

    # Trie (字典树) 别名
    "trie_insert": "trie_insert",
    "trie_add": "trie_insert",
    "trie_insert_word": "trie_insert",
    "trie_insert_words": "trie_insert",
    "insert_trie": "trie_insert",
    "add_to_trie": "trie_insert",
    "trie_add_word": "trie_insert",
    "trie_add_words": "trie_insert",
    
    "trie_search": "trie_search",
    "trie_find": "trie_search",
    "trie_lookup": "trie_search",
    "trie_search_word": "trie_search",
    "search_trie": "trie_search",
    "find_in_trie": "trie_search",
    "trie_query": "trie_search",
    "trie_contains": "trie_search",
    
    "trie_clear": "trie_clear",
    "trie_reset": "trie_clear",
    "clear_trie": "trie_clear",
    "reset_trie": "trie_clear",
    "empty_trie": "trie_clear",
    
    "trie_batch_create": "trie_batch_create",
    "trie_create": "trie_batch_create",
    "create_trie": "trie_batch_create",
    "build_trie": "trie_batch_create",
    "trie_build": "trie_batch_create",
    "make_trie": "trie_batch_create",
    
    "trie_get_state": "trie_get_state",
    "get_trie_state": "trie_get_state",
    "trie_state": "trie_get_state",
    "trie_get_words": "trie_get_state",
    "trie_words": "trie_get_state",
    "trie_list_words": "trie_get_state",

    # B+ 树别名
    "bplustree_insert": "bplustree_insert",
    "bplus_insert": "bplustree_insert",
    "bplus_add": "bplustree_insert",
    "bplustree_add": "bplustree_insert",
    "insert_bplustree": "bplustree_insert",
    "bplus_tree_insert": "bplustree_insert",
    "b_plus_insert": "bplustree_insert",
    
    "bplustree_search": "bplustree_search",
    "bplus_search": "bplustree_search",
    "bplus_find": "bplustree_search",
    "bplustree_find": "bplustree_search",
    "search_bplustree": "bplustree_search",
    "find_bplustree": "bplustree_search",
    "bplus_lookup": "bplustree_search",
    "bplus_query": "bplustree_search",
    
    "bplustree_clear": "bplustree_clear",
    "bplus_clear": "bplustree_clear",
    "clear_bplustree": "bplustree_clear",
    "bplus_reset": "bplustree_clear",
    "reset_bplustree": "bplustree_clear",
    
    "bplustree_batch_create": "bplustree_batch_create",
    "bplus_create": "bplustree_batch_create",
    "create_bplustree": "bplustree_batch_create",
    "bplus_build": "bplustree_batch_create",
    "build_bplustree": "bplustree_batch_create",
    "make_bplustree": "bplustree_batch_create",
    
    "bplustree_get_state": "bplustree_get_state",
    "get_bplustree_state": "bplustree_get_state",
    "bplus_get_state": "bplustree_get_state",
    "bplus_state": "bplustree_get_state",
    "bplus_leaves": "bplustree_get_state",
    "bplustree_leaves": "bplustree_get_state",

    # 散列表别名
    "hashtable_insert": "hashtable_insert",
    "hash_insert": "hashtable_insert",
    "hashtable_add": "hashtable_insert",
    "hash_add": "hashtable_insert",
    "insert_hashtable": "hashtable_insert",
    "hash_table_insert": "hashtable_insert",
    
    "hashtable_find": "hashtable_find",
    "hash_find": "hashtable_find",
    "hashtable_search": "hashtable_find",
    "hash_search": "hashtable_find",
    "search_hashtable": "hashtable_find",
    "find_hashtable": "hashtable_find",
    "hash_lookup": "hashtable_find",
    "hashtable_lookup": "hashtable_find",
    
    "hashtable_delete": "hashtable_delete",
    "hash_delete": "hashtable_delete",
    "hashtable_remove": "hashtable_delete",
    "hash_remove": "hashtable_delete",
    "delete_hashtable": "hashtable_delete",
    "remove_hashtable": "hashtable_delete",
    
    "hashtable_clear": "hashtable_clear",
    "hash_clear": "hashtable_clear",
    "clear_hashtable": "hashtable_clear",
    "hashtable_reset": "hashtable_clear",
    "hash_reset": "hashtable_clear",
    
    "hashtable_batch_create": "hashtable_batch_create",
    "hash_create": "hashtable_batch_create",
    "create_hashtable": "hashtable_batch_create",
    "hashtable_create": "hashtable_batch_create",
    "build_hashtable": "hashtable_batch_create",
    "make_hashtable": "hashtable_batch_create",
    
    "hashtable_get_state": "hashtable_get_state",
    "get_hashtable_state": "hashtable_get_state",
    "hash_get_state": "hashtable_get_state",
    "hashtable_state": "hashtable_get_state",
    "hash_state": "hashtable_get_state",
    
    "hashtable_resize": "hashtable_resize",
    "hash_resize": "hashtable_resize",
    "resize_hashtable": "hashtable_resize",
    
    "hashtable_switch": "hashtable_switch",
    "hash_switch": "hashtable_switch",
    "hashtable_switch_method": "hashtable_switch",
    "switch_hashtable": "hashtable_switch",
    "hashtable_toggle": "hashtable_switch",
    "toggle_hashtable_method": "hashtable_switch",
    "switch_collision_method": "hashtable_switch",
    
    "hashtable_set_hash": "hashtable_set_hash",
    "hash_set_hash": "hashtable_set_hash",
    "hashtable_hash": "hashtable_set_hash",
    "set_hash_function": "hashtable_set_hash",
    "hashtable_hash_function": "hashtable_set_hash",
}
